<?php
/**
 * Copyright (c) 2017 Vaimo Finland Oy, Suomen Maksuturva Oy
 * See LICENSE.txt for license details.
 */
?>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 vco-login vco-login-form">
        <h3 class="hidden-xs"><?php echo $this->__("I'm already a customer"); ?></h3>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <div class="vco-login-inner">
            <button id="js-vco-login-form-trigger" type="button" class="button vco-login-form-trigger visible-xs"><?php echo $this->__("I'm already a customer"); ?></button>
            <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post" class="vco-login-form-group">
                <?php echo $this->getBlockHtml('formkey'); ?>
                <ul class="vco-form">
                    <li>
                        <label for="login-email" class="required"><?php echo $this->__('Email Address') ?></label>
                        <input type="email" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
                    </li>
                    <li>
                        <label for="login-password" class="required"><?php echo $this->__('Password') ?></label>
                        <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    <li class="vco-buttons">
                        <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="vco-forgot-pwd"><?php echo $this->__('Forgot your password?') ?></a>
                        <button type="submit" class="button" onclick="onepageLogin(this)"><?php echo $this->__('Login') ?></button>
                    </li>
                </ul>
                <input name="context" type="hidden" value="checkout" />
            </form>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 vco-login vco-login-new">
        <h3><?php echo $this->__("I'm new here"); ?></h3>
        <?php echo $this->getChildHtml('login_before')?>

        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <div class="vco-login-inner">
                <button type="button" id="js-vco-login-guest" class="button" value="guest"><?php echo $this->__('Checkout as Guest') ?></button>
            </div>
        <?php endif; ?>
        <div class="vco-login-inner">
            <?php if ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
                <button type="button" id="onepage-guest-register-button" class="button" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'"><span><span><?php echo $this->__('Register') ?></span></span></button>
            <?php else: ?>
                <button type="button" id="js-vco-login-register" value="register" class="button"><?php echo $this->__('Register') ?></button>
            <?php endif; ?>
        </div>
        <input type="hidden" id="vco-checkout-method" name="checkout_method" value="<?php if( !$this->getQuote()->isAllowedGuestCheckout() ): ?>register<?php endif; ?>" />
    </div>
    <?php /* MASTERPASS BEST PRACTICE START */ ?>
    <?php if($this->getQuote()->isAllowedGuestCheckout()): ?>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 vco-login vco-login-new">
            <h3><?php echo $this->__("Pay immediately"); ?></h3>
            <?php echo $this->getChildHtml('mpbp_button'); ?>
        </div>
    <?php endif; ?>
    <?php /* MASTERPASS BEST PRACTICE END */ ?>
</div>
<script type="text/javascript">
    //<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
    //]]>
</script>
<?php
$registerParam = $this->getRequest()->getParam('register');
if ($registerParam || $registerParam === ''):
    ?>
    <script type="text/javascript">
        //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
        //]]>
    </script>
<?php endif; ?>