<?php
/**
 * Copyright (c) 2017 Vaimo Finland Oy, Suomen Maksuturva Oy
 * See LICENSE.txt for license details.
 */
?>
<?php if (! $this->isDisabled()): ?>
    <?php $buttonImageUrl = $this->getSkinUrl('images/mp_chk_btn_147x034px.svg'); ?>

    <?php if ($this->isInCartPage()): ?>
        <div class="mpbp-btn-label"><?php echo $this->__('Or pay immediately'); ?></div>
    <?php endif; ?>
    <div class="mpbp-btn">
        <a title="Masterpass Checkout" href="#">
            <img src="<?php echo $buttonImageUrl; ?>" class="btn-masterpass-checkout <?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"/>
        </a>

        <?php if ($additional = $this->getChild('additional')): ?>
            <?php echo $additional->toHtml(); ?>
        <?php endif; ?>
    </div>
<?php endif ?>
